server:
  AppVersion: 1.0.0-local
  Port: :5001
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbName: simple_auth_db
  PostgresqlSSLMode: false
  PgDriver: pgx

redis:
  RedisAddr: localhost:6379
  RedisPassword: 
  RedisDB: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

jaeger:
  Host: http://localhost:14268/api/traces
  ServiceName: AUTH_GRPC
  LogSpans: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

metrics:
  URL: 0.0.0.0:7070
  ServiceName: SIMPLE_AUTH_MICROSERVICE

rabbitmq:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchange: emails_exchange
  Queue: emails_queue
  RoutingKey: emails_routing_key
  ConsumerTag: emails_consumer
  WorkerPoolSize: 24

resend:
  ApiKey: re_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx